{
 "title": "Oversight",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(up{job=~\"$job\"},node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp59s0\"}[$__rate_interval]) / (1024*1024)",
     "legendFormat": "down"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"enp59s0\"}[$__rate_interval]) / (1024*1024)",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_name) (up{job=\"node\"})"
    }
   ]
  },
  {
   "title": "AMQ Artemis Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"activemq-artemis\"})"
    }
   ]
  },
  {
   "title": "Zookeeper Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "Kafka Broker Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Camel Quarkus Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"camelquarkus\"})"
    }
   ]
  }
 ]
}