server:
  http_listen_port: 80
  grpc_listen_port: 9095

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://215674:eyJrIjoiYTkxNzVhY2Y0ZDUyN2Y4NmVmZTkyNzRkNmI2NjNiY2Y2OWMzYzljZSIsIm4iOiJhbGFpbi1zdGFuZGFyZC1sb2tpIiwiaWQiOjY0MTQ4Mn0=@logs-prod-eu-west-0.grafana.net/loki/api/v1/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - regex:
      expression: "^(?s)(?P<borne_id>\\S+?) (?P<status>FAIL|OK) (?P<content>.*)$"
  - timestamp:
      source: time
      format: RFC3339Nano
  - labels:
      borne_id:
  - replace:
      expression: "(OK)"
      source: status
      replace: "1"
  - replace:
      expression: "(FAIL)"
      source: status
      replace: "0"
  - metrics:
      borne_state:
        type: Gauge
        description: current state of the borne
        source: status
        config: 
          action: set

  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log