#ingress 

- name: Create ingress controller namespace
  shell: kubectl apply -f /root/install/ingress-nginx-ns.yml

- name: create self signed certificate in kube
  shell: |
    kubectl create secret tls ingress-nginx-tls  --key="/root/install/tls/kube.loc.key"   --cert="/root/install/tls/kube.loc.crt" -n ingress-nginx  --dry-run=client -o yaml | kubectl apply -f -

- name: install ingress controller
  shell: kubectl apply -f /root/install/ingress-nginx-daemonset.yml
