---
- set_fact:
    appname: postgres

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'


- name: "Manage {{appname}} container state - {{appstate}} - {{ips[appname]}}"
  docker_container:
    name: "{{appname}}"
    image: postgres:14.3
    state: "{{appstate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    env:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    labels: |
      {
        "traefik.tcp.services.{{appname}}.loadbalancer.server.port": "61616",
        "traefik.tcp.routers.{{appname}}.entrypoints": "https",
        "traefik.tcp.routers.{{appname}}.tls": "true",
        "traefik.tcp.routers.{{appname}}.rule": "HostSNI(`{{appname}}.{{ansible_hostname}}.lan`)",
        "traefik.tcp.routers.{{appname}}.service": "{{appname}}",
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/amqdata:rw"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{ips[appname]}}"