---
- set_fact:
    appname: grafana-agent

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/config/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy config {{appname}} config
  copy:
    src: ./../{{appname}}/config/
    dest: /home/{{ ansible_user }}/apps/{{appname}}/config/
    mode: '0644'

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: "Manage {{appname}} container state - {{appstate}} - {{ips[appname]}}"
  docker_container:
    name: "{{appname}}"
    image: grafana/agent:v0.24.2
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "1000:1000"
    env:
    ports:
    labels: |
      {
        "traefik.enable": "false"
      }
    volumes:
      - /home/{{ ansible_user }}/apps/{{appname}}/config/agent.yml:/etc/agent/agent.yaml:ro
      - /home/{{ ansible_user }}/apps/{{appname}}/data:/etc/agent/data:rw
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{ips[appname]}}"