---
- set_fact:
    appname: prometheus

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/config/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy config {{appname}} config
  copy:
    src: templates/{{appname}}/config/
    dest: /home/{{ ansible_user }}/apps/{{appname}}/config/
    mode: '0644'

- name: "Manage {{appname}} container state - {{appstate}} - {{ips[appname]}}"
  docker_container:
    name: "{{appname}}"
    image: prom/prometheus:v2.35.0
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "1000:1000"
    env:
    ports:
    labels: |
      {
        "traefik.http.routers.{{appname}}.entrypoints": "http",
        "traefik.http.routers.{{appname}}.tls": "false"
      }
    volumes:
      - /home/{{ansible_user}}/apps/prometheus/data:/prometheus:rw
      - /home/{{ansible_user}}/apps/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{ips[appname]}}"